version: '3.7'

networks:
  internalDB:
  publicWeb:

services:
  Web:
    image: caddy/caddy:scratch
    restart: unless-stopped
    command: ['run', '--config', '/etc/caddy/Caddyfile.json']
    volumes:
      - ./Caddyfile.json:/etc/caddy/Caddyfile.json
      - staticWeb:/app/public/static:ro
      - tlsCertificates:/TLS:ro
    ports:
      - 8085:8085
      - 443:443
    networks:
      - publicWeb

  API:
    build:
      context: ./Services/API/
      dockerfile: Dockerfile.dev
    image: kristianfoss/development/app-template-api
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - internalDB
      - publicWeb
    volumes:
      # GIT
      - ./.git:/workspace/.git:cached
      - ./.gitignore:/workspace/.gitignore:ro

      # API Folders
      - ./Services/API:/workspace/Services/API:delegated
      - apiModules:/workspace/Services/API/node_modules
      # Other Services
      - ./Services/UI:/workspace/Services/UI:ro
      - ./Services/SSO:/workspace/Services/SSO:ro
      # GraphQL Schema File Generated By API
  #      - ./Schema.graphql:/workspace/Services/API/Schema.graphql:cached

  UI:
    build:
      context: ./Services/UI/
      dockerfile: Dockerfile.dev
    image: kristianfoss/development/app-template-ui
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      DOMAIN: 'localhost.kristianjones.dev'
    networks:
      - publicWeb
    volumes:
      # GIT
      - ./.git:/workspace/.git:cached
      - ./.gitignore:/workspace/.gitignore:cached

      # UI Folders
      - ./Services/UI:/workspace/Services/UI:delegated
      - uiModules:/workspace/Services/UI/node_modules
      - uiCache:/workspace/Services/UI/.parcel-cache
      - staticWeb:/workspace/Services/UI/dist/public

      # GraphQL Schema File Generated By API
      - ./Schema.graphql:/workspace/Services/UI/Schema.graphql:cached
      - ./local/AppTemplate.xml:/IDPMetadata.xml:ro

  SSO:
    build:
      context: ./Services/SSO/
      dockerfile: Dockerfile.dev
    image: kristianfoss/development/app-template-sso
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      DOMAIN: 'localhost.kristianjones.dev'
    networks:
      - publicWeb
    volumes:
      # GIT
      - ./.git:/workspace/.git:cached
      - ./.gitignore:/workspace/.gitignore:cached

      # UI Folders
      - ./Services/SSO:/workspace/Services/SSO:delegated
      - ssoModules:/workspace/Services/SSO/node_modules
      - ./local/AppTemplate.xml:/metadata.xml:ro

  SubscriberDL:
    image: docker.pkg.github.com/kristianfjones/distributed-dns/distributed-dns-subscriberdl
    restart: unless-stopped
    env_file: ENVs/SubscriberDL.env
    environment:
      API_URL: 'https://dns.kristianjones.dev'
    volumes:
      - subscriberDLState:/data/State
      - tlsCertificates:/data/TLS
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.ouroboros.enable: 'true'

  database:
    image: postgres:alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - internalDB
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: app-template

volumes:
  apiModules:
  uiModules:
  ssoModules:
  ssoDist:
  uiCache:
  databaseData:
  pgAdminData:
  staticWeb:
  tlsCertificates:
  subscriberDLState:
