version: '3.7'

networks:
  internalDB:
  publicWeb:

volumes:
  databaseData:

services:
  Web:
    image: caddy/caddy:scratch
    restart: unless-stopped
    command: ['run', '--config', '/etc/caddy/Caddyfile.json']
    volumes:
      - ./Caddyfile.json:/etc/caddy/Caddyfile.json
    ports:
      - 80:80
    networks:
      - publicWeb

  API:
    build:
      context: ../API/
      dockerfile: Dockerfile
    image: kristianfoss/prod/app-template-api
    restart: unless-stopped
    networks:
      - internalDB
      - publicWeb

  database:
    image: postgres:alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    networks:
      - internalDB
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: app-template
